title: "Eddie Coda"
logo: "/assets/images/headshot.png?raw=true"
description: "LinkedIn: [your-linkedin-url-here] | GitHub: https://github.com/codaeddie - B.S., Computer Science | San Diego State University (December 2023) - Recent Software Engineering graduate with background in Home Automation, and a focus on NLP and Deep Learning research."
show_downloads: false
theme: jekyll-theme-minimal


google_analytics: G-KWZDNPELG2 # your Google Analytics tracking ID here

