title: "Eddie Coda"
logo: "/assets/images/123me.png?raw=true"
description: "[Resume](https://github.com/codaeddie/portfolio/blob/main/pdf/edcodaresume.pdf){: .btn .btn--info}| LinkedIn: [https://www.linkedin.com/in/edmund-coda-61377a100/] | GitHub: https://github.com/codaeddie - B.S., Computer Science | San Diego State University (December 2023) - Recent Software Engineering graduate with background in Home Automation, and a focus on NLP and Deep Learning research."
show_downloads: false
theme: jekyll-theme-minimal


google_analytics: G-KWZDNPELG2 # your Google Analytics tracking ID here

